### ISSUE TITLE
ImportError: cannot import name 'Literal' from 'typing' 

### ISSUE THREAD

**Issue by henning101** [ImNimboss/uberduck#5]
## Description
Hi! 

I get the following exception when trying to run the Uberduck API. The issue wasn't there before and I read that it could be caused by Python 3.7 not supporting the Literal library. Is there a way around this or do I have to update to Python 3.8?

```
  File ".../venv/lib/python3.7/site-packages/uberduck/__init__.py", line 12, in <module>
    from uberduck.main import UberDuck, get_voices, get_voices_async
  File ".../venv/lib/python3.7/site-packages/uberduck/main.py", line 13, in <module>
    from typing import Union, Literal, Optional, List
ImportError: cannot import name 'Literal' from 'typing' (/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/typing.py)
```

Edit:
I removed the Literal import from line 13 of main.py in the uberduck package and added this below:
```
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
```
This makes it work in Python 3.7 as well.

## Reproduction steps
Include the Uberduck API in Python 3.7.9

## Expected result
The program runs

## Actual result
Python exception shows

## Uberduck version
0.0.4

## Operating system
MacOS Ventura 13.3.1 (a)

**Comment by ImNimboss** [comment]
Ah okay, I'll fix this

**Comment by ImNimboss** [comment]
Uberduck version `v.0.0.5` has been released which adds the if statement given above and installs `typing_extensions` if the python version is below 3.8, happy coding :)

**Comment by henning101** [comment]
> Uberduck version `v.0.0.5` has been released which adds the if statement given above and installs `typing_extensions` if the python version is below 3.8, happy coding :)

Cool!! Thank you :) I'll fetch the latest version!
